/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package majorprogram1;

import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author Camden Wade
 */
public class AggieBank extends javax.swing.JFrame {

    /**
     * Creates new form AggieBank
     */
    //Instance of CyberBank
    CyberBank cyberBank;
    String inputFile;
    String outputFile;
    Customer bankCustomer = new Customer();

    public AggieBank(CyberBank cyberBank, String inputFile) {
        initComponents();

        this.cyberBank = cyberBank;
        this.inputFile = inputFile;
        this.outputFile = inputFile;
        withdrawJbutton.setEnabled(false);
        depositJbutton.setEnabled(false);
        TransferJbutton.setEnabled(false);
        balanceJbutton.setEnabled(false);
        saveJbutton.setEnabled(false);
        logoffJbutton.setEnabled(false);
        accountInfoJList1.setVisible(false);
        pack();
    }

    public AggieBank(CyberBank cyberBank, String inputFile, String outputFile) {
        initComponents();
        this.cyberBank = cyberBank;
        this.inputFile = inputFile;
        this.outputFile = outputFile;        
        withdrawJbutton.setEnabled(false);
        depositJbutton.setEnabled(false);
        TransferJbutton.setEnabled(false);
        balanceJbutton.setEnabled(false);
        saveJbutton.setEnabled(false);
        logoffJbutton.setEnabled(false);
        accountInfoJList1.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        bankNameLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        exitJbutton = new javax.swing.JButton();
        logoffJbutton = new javax.swing.JButton();
        saveJbutton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        withdrawJbutton = new javax.swing.JButton();
        depositJbutton = new javax.swing.JButton();
        TransferJbutton = new javax.swing.JButton();
        balanceJbutton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        customerIdLabel = new javax.swing.JLabel();
        pinLabel = new javax.swing.JLabel();
        customerIdTextfield = new javax.swing.JTextField();
        pinTextfield = new javax.swing.JTextField();
        logonJbutton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        accountInfoJList1 = new javax.swing.JList<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 600));

        bankNameLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bankNameLabel.setText("AggieBank");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, java.awt.Color.yellow));

        exitJbutton.setText("Exit");
        exitJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitJbuttonActionPerformed(evt);
            }
        });

        logoffJbutton.setText("Logoff");
        logoffJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoffJbuttonActionPerformed(evt);
            }
        });

        saveJbutton.setText("Save");
        saveJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveJbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saveJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logoffJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(logoffJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(exitJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.yellow, java.awt.Color.yellow));

        withdrawJbutton.setText("Withdraw");
        withdrawJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawJbuttonActionPerformed(evt);
            }
        });

        depositJbutton.setText("Deposit");
        depositJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositJbuttonActionPerformed(evt);
            }
        });

        TransferJbutton.setText("Transfer");
        TransferJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferJbuttonActionPerformed(evt);
            }
        });

        balanceJbutton.setText("Balance");
        balanceJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceJbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(depositJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TransferJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(balanceJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdrawJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(withdrawJbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(depositJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TransferJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(balanceJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.black));

        customerIdLabel.setText("Customer ID:");

        pinLabel.setText("PIN:");

        pinTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinTextfieldActionPerformed(evt);
            }
        });

        logonJbutton.setText("Login");
        logonJbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logonJbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pinLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pinTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE)
                    .addComponent(customerIdTextfield))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(230, Short.MAX_VALUE)
                .addComponent(logonJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(206, 206, 206))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(customerIdTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pinTextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(pinLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logonJbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        accountInfoJList1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.yellow));
        accountInfoJList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {  };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(accountInfoJList1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(234, 234, 234)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(881, 881, 881)
                        .addComponent(bankNameLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(358, 358, 358)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bankNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void withdrawJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawJbuttonActionPerformed
        // TODO add your handling code here:
         String[] accountNumbers = new String[bankCustomer.getNumAccounts() + 1];
        for (int i = 0; i < bankCustomer.getNumAccounts(); i++) {
            accountNumbers[i] = bankCustomer.getAccounts(i).getAccountNumber();
        }
        Account account = null;
        String an = (String) JOptionPane.showInputDialog(this, "Choose Account", "Withdrawal", JOptionPane.PLAIN_MESSAGE, null, accountNumbers, accountNumbers[0]);
        for (int j = 0; j < bankCustomer.getNumAccounts(); j++) {
            if (an.equals(bankCustomer.getAccounts(j).getAccountNumber())) {
                account = bankCustomer.getAccounts(j);
            }
        }

        String withdrawAmount = JOptionPane.showInputDialog(null, "Enter amount you want to withdraw", "Withdrawal", JOptionPane.PLAIN_MESSAGE);
        double withdraw = Double.parseDouble(withdrawAmount);
        if (withdraw > 0.0 && withdraw <= account.getBalance()) {
            Transaction t = new Transaction();
            t.setAmount(withdraw);
            t.setDescription("You withdrew money");
            t.setTransactionType(TransactionType.debit);
            SimpleDateFormat form = new SimpleDateFormat();
            Date rightNow = new Date();
            t.setDate(form.format(rightNow));
            account.addTransaction(t);
        }
                                                  
        

    }//GEN-LAST:event_withdrawJbuttonActionPerformed

    private void logonJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logonJbuttonActionPerformed
        int idInput = Integer.parseInt(customerIdTextfield.getText());
        int pinInput = Integer.parseInt(pinTextfield.getText());
        bankCustomer = cyberBank.authenticateCustomer(idInput, pinInput);

        if (bankCustomer == null) {
            JOptionPane.showMessageDialog(null, "ID and PIN = WRONG!!!", "AMNESIA??? Try again fool", JOptionPane.PLAIN_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Whats GOOOOD !!!!! Welcome to the Aggie Bank B-B-B-B-BOSSSSSSSSSS", " ", JOptionPane.PLAIN_MESSAGE);
            String[] holder = new String[bankCustomer.getNumAccounts() + 1];
            String bc = bankCustomer.getFirstName() + " " + bankCustomer.getLastName();
            holder[0] = bc;
            for (int i = 0; i < bankCustomer.getNumAccounts(); i++) {
                holder[i + 1] = bankCustomer.getAccounts(i).getAccountType().toString() + bankCustomer.getAccounts(i).getAccountNumber();
            }
            accountInfoJList1.setListData(holder);
            withdrawJbutton.setEnabled(true);
            depositJbutton.setEnabled(true);
            TransferJbutton.setEnabled(true);
            balanceJbutton.setEnabled(true);
            saveJbutton.setEnabled(true);
            logoffJbutton.setEnabled(true);
            accountInfoJList1.setVisible(true);
            customerIdLabel.setVisible(false);
            pinLabel.setVisible(false);
            customerIdTextfield.setVisible(false);
            pinTextfield.setVisible(false);
            logonJbutton.setVisible(false);
            jPanel5.setVisible(false);

        }


    }//GEN-LAST:event_logonJbuttonActionPerformed

    private void exitJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitJbuttonActionPerformed

        System.exit(-1); // Exit GUI
    }//GEN-LAST:event_exitJbuttonActionPerformed

    private void saveJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveJbuttonActionPerformed
        // TODO add your handling code here:
        cyberBank.saveBankData(outputFile);
        
    }//GEN-LAST:event_saveJbuttonActionPerformed

    private void pinTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pinTextfieldActionPerformed

    private void logoffJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoffJbuttonActionPerformed
        // TODO add your handling code here:
        accountInfoJList1.setVisible(false);

    }//GEN-LAST:event_logoffJbuttonActionPerformed

    private void balanceJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceJbuttonActionPerformed
        // TODO add your handling code here:

        String accountBalances = "";
        for (int i = 0; i < bankCustomer.getNumAccounts(); i++) {
            accountBalances += bankCustomer.getAccounts(i).getBalance() + " " + bankCustomer.getAccounts(i).getAccountNumber() + System.lineSeparator();
        }
        JOptionPane.showMessageDialog(this, accountBalances, "Your balances", JOptionPane.PLAIN_MESSAGE);  //.showMessageDialog(this, accountBalances);

    }//GEN-LAST:event_balanceJbuttonActionPerformed

    private void depositJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositJbuttonActionPerformed
        // TODO add your handling code here:
        String[] accountNumbers = new String[bankCustomer.getNumAccounts() + 1];
        for (int i = 0; i < bankCustomer.getNumAccounts(); i++) {
            accountNumbers[i] = bankCustomer.getAccounts(i).getAccountNumber();
        }
        Account account = null;
        String an = (String) JOptionPane.showInputDialog(this, "Choose Account", "Deposit", JOptionPane.PLAIN_MESSAGE, null, accountNumbers, accountNumbers[0]);
        for (int j = 0; j < bankCustomer.getNumAccounts(); j++) {
            if (an.equals(bankCustomer.getAccounts(j).getAccountNumber())) {
                account = bankCustomer.getAccounts(j);
            }
        }

        String depositAmount = JOptionPane.showInputDialog(null, "Enter amount you want to deposit", "Deposit", JOptionPane.PLAIN_MESSAGE);
        double deposit = Double.parseDouble(depositAmount);
        if (deposit > 0.0) {
            Transaction t = new Transaction();
            t.setAmount(deposit);
            t.setDescription("You deposited money");
            t.setTransactionType(TransactionType.credit);
            SimpleDateFormat form = new SimpleDateFormat();
            Date rightNow = new Date();
            t.setDate(form.format(rightNow));
            account.addTransaction(t);
        }
    }//GEN-LAST:event_depositJbuttonActionPerformed

    private void TransferJbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferJbuttonActionPerformed
        // TODO add your handling code here:
         String[] accountNumbers = new String[bankCustomer.getNumAccounts() + 1];
        for (int i = 0; i < bankCustomer.getNumAccounts(); i++) {
            accountNumbers[i] = bankCustomer.getAccounts(i).getAccountNumber();
        }
        Account account = null;
        String an = (String) JOptionPane.showInputDialog(this, "Choose Account", "Transfer", JOptionPane.PLAIN_MESSAGE, null, accountNumbers, accountNumbers[0]);
        for (int j = 0; j < bankCustomer.getNumAccounts(); j++) {
            if (an.equals(bankCustomer.getAccounts(j).getAccountNumber())) {
                account = bankCustomer.getAccounts(j);
            }
        }

        String transferAmount = JOptionPane.showInputDialog(null, "Enter amount you want to transfer", "transfer", JOptionPane.PLAIN_MESSAGE);
        double transfer = Double.parseDouble(transferAmount);
        if (transfer > 0.0 && transfer <= account.getBalance()) {
            Transaction t = new Transaction();
            t.setAmount(transfer);
            t.setDescription("You transferred money");
            t.setTransactionType(TransactionType.transfer);
            SimpleDateFormat form = new SimpleDateFormat();
            Date rightNow = new Date();
            t.setDate(form.format(rightNow));
            account.addTransaction(t);
        }
                           
        
    }//GEN-LAST:event_TransferJbuttonActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(AggieBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(AggieBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(AggieBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(AggieBank.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new AggieBank().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton TransferJbutton;
    private javax.swing.JList<String> accountInfoJList1;
    private javax.swing.JButton balanceJbutton;
    private javax.swing.JLabel bankNameLabel;
    private javax.swing.JLabel customerIdLabel;
    private javax.swing.JTextField customerIdTextfield;
    private javax.swing.JButton depositJbutton;
    private javax.swing.JButton exitJbutton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoffJbutton;
    private javax.swing.JButton logonJbutton;
    private javax.swing.JLabel pinLabel;
    private javax.swing.JTextField pinTextfield;
    private javax.swing.JButton saveJbutton;
    private javax.swing.JButton withdrawJbutton;
    // End of variables declaration//GEN-END:variables
}
